### PR TITLE
added get_train_composition_string

### PR DESCRIPTION
**Pull request by eduran84**
I added another function. Not sure if you are happy with the local functions. You would have to (slightly) change how you include them in your mods. If you prefer global functions I can also upload a version without added local tags.

### CODE REVIEW

**Comment by 0ptera** [comment]
Thanks for also fixing my copy pasta errors.

I'd add A for artillery wagon, so this function is capable of handling all carriage types.

Did you benchmark if localizing in a library is any faster than just localizing the call to the library function?
If it doesn't offer benefits just having that return block is a needless potential error.

**Comment by eduran84** [comment]
> Did you benchmark if localizing in a library is any faster than just localizing the call to the library function?
If it doesn't offer benefits just having that return block is a needless potential error.

I don't think it makes a difference for performance (but did not benchmark). As long as it is local when you are using it it should not matter how it was localized.

The advantages I see are:
1. The functions don't pollute the global namespace (Yes, i know... doesn't matter for our use case, but I can't stop being a nitpicker)
2. The return-block makes it so I can do
` local train_util = require("__OpteraLib__.misc.train")`
and access every function through the util table. Again, not really important, just something I like to do.

I've uploaded a version with a different approach. Should be less error-prone and have the same result. But you are using the library more than I am, so ultimately it has to suit your needs. I could live with the way you implemented it originally.

> I'd add A for artillery wagon, so this function is capable of handling all carriage types.

Done

**Comment by 0ptera** [comment]
I like this way of calling it.
Hopefully this won't require me to change all existing mods relying on the lib.

**Comment by 0ptera** [comment]
Reverted changes to function names.
I don't feel like changing all my mods using the library.

PS: localizing each function directly should be marginally faster than accessing through a table.

**Pull request merged**
